name: smart-home

services:
  mysql:
    image: mysql:8.0
    container_name: smart-home-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_home
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30

  mongodb:
    image: mongo:7
    container_name: smart-home-mongo
    environment:
      TZ: Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  emqx:
    image: emqx/emqx:5
    container_name: smart-home-emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: public
      TZ: Asia/Shanghai

